#
# Copyright (C) 2020-2022 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-protocol"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
signal-crypto = { path = "../crypto" }
aes = { version = "0.8.3", features = ["zeroize"] }
aes-gcm-siv = "0.11.1"
arrayref = "0.3.6"
async-trait = "0.1.41"
ctr = { version = "0.9.2", features = ["zeroize"] }
curve25519-dalek = { version = "4.0.0" }
hkdf = "0.12"
hmac = "0.12"
itertools = "0.10.5"
prost = "0.9"
rand = "0.8"
sha2 = "0.10"
static_assertions = "1.1"
subtle = "2.3"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
hex = "0.4"
log = "0.4"
num_enum = "0.6.1"
uuid = "1.1.2"
displaydoc = "0.2"
thiserror = "1.0.30"
pqcrypto-kyber = { version = "0.7.6", default-features = false, features = ["std"] }
pqcrypto-traits = "0.3.4"

[features]
whisperfork = []

[dev-dependencies]
criterion = "0.5"
hex-literal = "0.4.1"
proptest = "1.0"
futures-util = "0.3.7"
env_logger = "0.10.0"

[build-dependencies]
prost-build = "0.9"

[[bench]]
name = "curve"
harness = false

[[bench]]
name = "session"
harness = false

[[bench]]
name = "ratchet"
harness = false

[[bench]]
name = "sealed_sender"
harness = false

[[bench]]
name = "kem"
harness = false
