#
# Copyright (C) 2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "signal-crypto"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"

[dependencies]
aes = { version = "0.7.4", features = ["armv8", "ctr"] }
subtle = "2.3"
generic-array = "0.14"
ghash = { version = "0.4.2", features = ["armv8"] }
hmac = "0.9.0"
sha-1 = "0.9"
sha2 = "0.9"

[dev-dependencies]
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
criterion = "0.3"

[[bench]]
name = "aes_gcm"
harness = false
