#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

# This is a separate crate so we can run the Neon build script.

[package]
name = "signal-neon-futures-tests"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
signal-neon-futures = { path = ".." }
neon = { version = "0.10.0", default-features = false, features = ["napi-1"] }
futures-util = "0.3.7"

[features]
# Enable default-panic-hook to get backtraces of panics.
default = []
default-panic-hook = []
