#
# Copyright (C) 2023 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "usernames"
authors = ["Signal Messenger LLC"]
version = "0.1.0"
edition = "2018"
description = "A zero-knowledge usernames library"
license = "AGPL-3.0-only"

[dependencies]
poksho = { path = "../poksho" }

sha2 = "0.9.0"
displaydoc = "0.2"
lazy_static = "1.4.0"
rand = "0.7.3"

[dependencies.curve25519-dalek]
features = ["serde"]
version = "3.0.0"
git = "https://github.com/signalapp/curve25519-dalek.git"
branch = "lizard2"

[dev-dependencies]
zkgroup = { path = "../zkgroup" }
proptest = "1.0"
