#
# Copyright (C) 2023 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "usernames"
authors = ["Signal Messenger LLC"]
version = "0.1.0"
edition = "2018"
description = "A zero-knowledge usernames library"
license = "AGPL-3.0-only"

[dependencies]
poksho = { path = "../poksho" }
signal-crypto = { path = "../crypto" }

curve25519-dalek = "3.2"
hkdf = "0.11"
sha2 = "0.9.0"
displaydoc = "0.2"
lazy_static = "1.4.0"
prost = "0.9"
rand = "0.7.3"
thiserror = "1.0.40"

[dev-dependencies]
zkgroup = { path = "../zkgroup" }
proptest = "1.0"
criterion = "0.4"

[[bench]]
name = "usernames_benchmarks"
harness = false

[build-dependencies]
prost-build = "0.9"
