#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
libsignal-protocol = { path = "../../protocol" }
signal-crypto = { path = "../../crypto" }
device-transfer = { path = "../../device-transfer" }
attest = { path = "../../attest" }
zkgroup = { path = "../../zkgroup" }
usernames = { path = "../../usernames" }
signal-pin = { path = "../../pin" }
signal-media = { path = "../../media", optional = true }
libsignal-bridge-macros = { path = "macros" }
aes-gcm-siv = "0.11.1"
async-trait = "0.1.41"
bincode = "1.0"
futures-util = "0.3.7"
hkdf = "0.12"
hmac = "0.12.0"
log = "0.4"
paste = "1.0"
rand = "0.8"
scopeguard = "1.0"
serde = "1.0"
sha2 = "0.10"
static_assertions = "1.1"
uuid = "1.1.2"

bytemuck = { version = "1.13.0", optional = true }
libc = { version = "0.2", optional = true }
jni_crate = { version = "0.19", package = "jni", optional = true }
neon = { version = "0.10.0", optional = true, default-features = false, features = ["napi-6", "promise-api"] }
linkme = { version = "0.3.9", optional = true }
signal-neon-futures = { path = "../node/futures", optional = true }

[features]
ffi = ["libc", "libsignal-bridge-macros/ffi"]
jni = ["jni_crate", "libsignal-bridge-macros/jni", "bytemuck"]
node = ["neon", "linkme", "signal-neon-futures", "libsignal-bridge-macros/node"]
