#
# Copyright 2020-2022 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "zkgroup"
version = "0.9.0"
authors = ["Trevor Perrin <trevp@signal.org>"]
edition = "2018"
description = "A zero-knowledge group library"
license = "AGPL-3.0-only"

[dependencies]
poksho = { path = "../poksho" }

bincode = "1.2.1"
serde = { version = "1.0.106", features = ["derive"] }
sha2 = "0.9.0"
hex = "0.4.0"
aead = "0.4.0"
aes-gcm-siv = "0.10.0"
displaydoc = "0.2"
lazy_static = "1.4.0"

# For generation
base64 = { version = "0.13.0", optional = true }
rand = { version = "0.7.3", optional = true }

[dependencies.curve25519-dalek]
features = ["serde"]
version = "3.0.0"
git = "https://github.com/signalapp/curve25519-dalek.git"
branch = "lizard2"

[features]
whisperfork = []

# Below is for benchmarking:

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "zkgroup_benchmarks"
harness = false

[[bin]]
name = "generate-server-params"
required-features = ["base64", "rand"]
