name: Slow Tests

on:
  schedule:
    # "High load times include the start of every hour.
    #  To decrease the chance of delay, schedule your workflow to run
    #  at a different time of the hour."
    # We pick 8:25 UTC, aiming for "later than PST/UTC-8 night work" and
    # "earlier than ADT/UTC-3 morning work".
    - cron: '25 8 * * *'
  workflow_dispatch: {} # no parameters

jobs:
  check-up-to-date:
    name: Already up to date?
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    outputs:
      has-changes: ${{ steps.check.outputs.has-changes }}
    steps:
    - uses: actions/checkout@v2
    - run: git log --after '24 hours ago' --exit-code || echo '::set-output name=has-changes::true'
      id: check

  java-docker:
    name: Java (Docker)
    runs-on: ubuntu-latest
    needs: [check-up-to-date]
    if: ${{ always() && (needs.check-up-to-date.outputs.has-changes || needs.check-up-to-date.result == 'skipped') }}

    steps:
    - uses: actions/checkout@v2
    - run: make -C java java_test

  node-docker:
    name: Node (Ubuntu via Docker)
    runs-on: ubuntu-latest
    needs: [check-up-to-date]
    if: ${{ always() && (needs.check-up-to-date.outputs.has-changes || needs.check-up-to-date.result == 'skipped') }}

    steps:
    - uses: actions/checkout@v2
    - run: node/docker-prebuildify.sh

  swift_cocoapod:
    name: Swift CocoaPod (with Catalyst)
    runs-on: macOS-latest
    needs: [check-up-to-date]
    if: ${{ always() && (needs.check-up-to-date.outputs.has-changes || needs.check-up-to-date.result == 'skipped') }}

    steps:
      - uses: actions/checkout@v2

      - name: Check out SignalCoreKit
        uses: actions/checkout@v2
        with:
          repository: signalapp/SignalCoreKit
          path: SignalCoreKit

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rust-src

      - name: Add iOS targets
        run: rustup target add x86_64-apple-ios aarch64-apple-ios aarch64-apple-ios-sim

      - name: Run pod lint
        # No import validation because it tries to build unsupported platforms (like 32-bit iOS).
        run: pod lib lint --verbose --platforms=ios --include-podspecs=SignalCoreKit/SignalCoreKit.podspec --skip-import-validation
